document.getElementById("BG1button").addEventListener("click",function(){
    document.getElementById("ch1").style.backgroundImage="url(imgs/i1.jpg)";
    document.getElementById("ch1").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i1.jpg)"
    });
    document.getElementById("ch2").style.backgroundImage="url(imgs/i2.jpg)";
    document.getElementById("ch2").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i2.jpg)"
    });
    document.getElementById("ch3").style.backgroundImage="url(imgs/i3.jpg)";
    document.getElementById("ch3").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i3.jpg)"
    });
});
document.getElementById("BG2button").addEventListener("click",function(){
    document.getElementById("ch1").style.backgroundImage="url(imgs/i4.jpg)";
    document.getElementById("ch1").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i4.jpg)"
    });
    document.getElementById("ch2").style.backgroundImage="url(imgs/i5.jpg)";
    document.getElementById("ch2").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i5.jpg)"
    });
    document.getElementById("ch3").style.backgroundImage="url(imgs/i6.jpg)";
    document.getElementById("ch3").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i6.jpg)"
    });
});
document.getElementById("BG3button").addEventListener("click",function(){
    document.getElementById("ch1").style.backgroundImage="url(imgs/i7.jpg)";
    document.getElementById("ch1").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i7.jpg)"
    });
    document.getElementById("ch2").style.backgroundImage="url(imgs/i8.jpg)";
    document.getElementById("ch2").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i8.jpg)"
    });
    document.getElementById("ch3").style.backgroundImage="url(imgs/i9.jpg)";
    document.getElementById("ch3").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i9.jpg)"
    });
});
document.getElementById("BG4button").addEventListener("click",function(){
    document.getElementById("ch1").style.backgroundImage="url(imgs/i10.jpg)";
    document.getElementById("ch1").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i10.jpg)"
    });
    document.getElementById("ch2").style.backgroundImage="url(imgs/i11.jpg)";
    document.getElementById("ch2").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i11.jpg)"
    });
    document.getElementById("ch3").style.backgroundImage="url(imgs/i12.jpg)";
    document.getElementById("ch3").addEventListener("mouseenter",function(){
        document.getElementById("zoom").style.backgroundImage="url(imgs/i12.jpg)"
    });
});
